config/routes.rb
Rails.application.routes.draw do

  get "/" => 'home#index'
  post "/send_text_message" =>"text_messages#send_text_message"

  get "/users/check_messages" => "users#check_messages"

  resources :sessions, only: [:new, :create, :destroy]

  resources :users, except: :delete do
    resources :dogs, only: [:index, :create, :delete]
  end

  resources :messages, only: [:new, :create, :show, :index] do
    resources :comments, module: :messages

  end

  resources :direct_conversations, only: [:index, :show, :new, :create] do
    resources :private_messages, only: [:create]
  end

  resources :dogs, except: [:create, :edit, :delete] do
    resources :dog_connections, only: [:new, :create, :delete]
  end

  resources :events do
    resources :comments, module: :events
    resources :event_invitations, only: [:create, :destroy]
  end

  resources :maps, only: [:index]
  get '/maps/data' => 'maps#data'
  get '/maps/pet_stores' => 'maps#pet_stores'
  get '/maps/dog_parks' => 'maps#dog_parks'
  post '/users/sync_location' => 'users#sync_location'

  post '/dogs/sync_location' => 'dogs#sync_location'

  get '/users' => 'user#index'

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  validates :owner_id, presence: true
  validates :name, presence: true

  has_many  :dog_connections
  has_many :followings, through: :dog_connections, foreign_key: "follower_id"

  has_many :event_invitations, foreign_key: "invitee_id"

  belongs_to  :owner, class_name: :User

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates_attachment_file_name :avatar, matches: [/png\Z/, /PNG\Z/, /jpe?g\Z/, /JPE?G\Z/]

  def followers
    followed = Dog.find_by_id(self.id)
    connections = DogConnection.where(:following => followed)
    connections.collect{|connection| connection.dog}
  end

   def find_good_dogs
    @good_dogs = []
    @friends = DogConnection.where(relationship_status: 1, dog_id: self.id).all
    @friends.each do |friend|
      @good_dogs << Dog.find_by(id: friend.following_id)
    end
    @good_dogs
   end

  def find_bad_dogs()
    @bad_dogs = []
    @enemies = DogConnection.where(relationship_status: -1, dog_id: self.id).all
    @enemies.each do |enemy|
      @bad_dogs << Dog.find_by(id: enemy.following_id)
    end
    @bad_dogs
  end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  include ApplicationHelper

  def index
     if current_user
      @forecast_data = forecast_data
      @user = current_user
      if params[:search]
        @found_dogs = search(params[:search])
        if @found_dogs.length == 1
          redirect_to "/dogs/#{@found_dogs[0].id}"
        else
          dog = @found_dogs.sample
          redirect_to "/dogs/#{dog.id}"
        end
      else
        @dogs = @user.dogs
      end
     else
        redirect_to "/sessions/new"
     end
  end

  def new
      if session[:user_id] == nil
        redirect_to "/sessions/new"
      end
      @user = User.find_by(id: session[:user_id])
  end

  def create
    @user = User.find_by(id: session[:user_id])
    @dog = Dog.create!(dog_params)
    if @dog.save
      redirect_to "/dogs/#{@dog.id}"
    else
      render :new
    end
  end

  def show
      if session[:user_id] != nil
        @dog = Dog.find(params[:id])
        @user = User.find_by(id: @dog.owner_id)
      else
        redirect_to "/sessions/new"
      end
  end

  def update
    @user = User.find(session[:user_id])
    @dog = Dog.find(params[:id])
    if request.xhr?
      @dogs = @user.dogs
      @dogs.each do |dog|
        dog.followings << @dog
        @dog.followers << dog
      end
      p @dog.followers
    else

      if @dog.update(dog_params)
        redirect_to "/dogs/#{@dog.id}"
      else
        redirect_to "/users/#{@user.id}/dogs"
      end
    end
  end

  def destroy
    @user = User.find_by(id: session[:user_id])
    @dog = Dog.find_by(id: params[:id])
    if @user.id != session[:user_id]
      redirect_to "/"
    else
      @dog.destroy
      redirect_to "/users/#{@user.id}"
    end
  end

  def sync_location
     if session[:user_id]
      if request.xhr?
       lat = params['location']['lat'].to_f
       lng = params['location']['lat'].to_f
       @user = User.find_by(id: current_user.id)
       @user.update_attributes(lat: lat, lng: lng)
       dog_id = params["id"].to_i
       render :show
      end
    end
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :bio, :owner_id, :avatar)
  end
end

app/helpers/dogs_helper.rb
module DogsHelper
	

end

app/views/dogs/_edit.html.erb
<div class="container">
  <div class="row">
    <%= form_for(:dog, method: "put",url: dog_path(dog), :html => {:class => "col s12"}) do |f| %>
      <div class="row">
        <div class="input-field col s6">
          <%= f.label :name %>
          <%= f.text_field :name, :value => dog.name %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.label :bio %>
          <%= f.text_area :bio, :value => dog.bio, :class => "materialize-textarea" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
        <%= f.file_field :avatar, :value => "upload picture" %>
        </div>
      </div>
      <%= f.hidden_field :owner_id, :value => @user.id %>
      <%= f.submit(:class => "btn", :value => "Edit")%>
    <% end %>
  </div>
</div>

app/views/dogs/_new.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <%= form_for(:dog, url: user_dogs_path(@user.id), :html => {:class => "col s12"}) do |f| %>
        <div class="row">
          <div class="input-field col s6">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s6">
            <%= f.label :bio %>
            <%= f.text_field :bio %>
          </div>
        </div>
        <div class="file-field input-field avatar">
          <div class="btn light-blue">
              <span>Upload Profile Picture</span>
             <%= f.file_field :avatar %>
          </div>
          <input class="file-path validate" type="text"/>
        </div>
        <%= f.hidden_field :owner_id, :value => current_user.id %>
        <%= f.submit(:class => "btn light-blue", :value => "Register" )%>
      <% end %>
    </div>
  </div>
</div>

app/views/dogs/_profile.html.erb
<div class="section">
  <h1><%= dog.name %></h1>
  <div class="row">
    <div class="col s4">
      <a href="/dogs/<%= dog.id %>">
        <%= image_tag dog.avatar.url(:medium, :class => "circle responsive-img") %>
      </a>
    </div>
    <div class="col s8">
      <ul class="collapsible" data-collapsible="accordion">
      <li>
        <div class="collapsible-header" style="padding-left: 45px;">Dogs <%= dog.name %> Follows</div>
        <div class="collapsible-body">
          <ul class="collection">
            <% find_good_dogs(dog).each do |friend| %>
              <li class="collection-item avatar">
                <span><a href="/dogs/<%= friend.id %>"><%=friend.name%>
                </a></span>
              </li>
            <% end %>
          </ul>
        </div>
      </li>
      <li>
        <div class="collapsible-header" style="padding-left: 45px;">Edit <%= dog.name %></div>
        <div class="collapsible-body">
          <%= render partial: "edit", locals: {dog: dog} %>
        </div>
      </li>
      <li>
        <div class="collapsible-header">
          <%= form_for :dog, url: dog_path(dog), method: "delete" do |f| %>
            <%= f.submit value: "Remove From Pack", :class => "btn-flat", :style => "text-transform: capitalize;" %>
          <% end %>
        </div>
      </li>
    </ul>
    </div>
  </div>
  <div id="twilio-messaging">
    <%= button_to "Send Emergency Alert", send_text_message_path(:user_numbers => text_users, :dog => dog.name), :class => "btn red"%>
  </div>
</div>
<div class="divider"></div>

app/views/dogs/index.html.erb
<div class="container">
  <%= form_tag(dogs_path, :method => "get", class: "row", id: "search-form") do %>
    <div class="col s12 m6 l4 offset-l8">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Find Dogs" %>
      <button class="btn light-blue" type="submit" value="search"><i class="material-icons left">search</i>Search All Dogs</button>
    </div>
  <% end %>
  <% if @found_dogs %>
    <% @found_dogs.each do |dog|%>
      <a href="/dogs/<%= dog.id%>"><%= dog.name %></a>
    <% end %>
  <% end %>
  <h1 class="center"><%= @user.username %>'s Pack</h1>
  <div class="row">
    <div class="col s12 m6 l4">
      <div class="card" id="weather-card">
        <div class="center">
          <p>Current Weather</p>
          <p id="summary"><%= @forecast_data["currently"]["summary"] %></p>
          <p>Current Temp: <%= @forecast_data["currently"]["temperature"].to_i %> &deg;F</p>
          <p>Chance of Rain: <%= @forecast_data["currently"]["precipProbability"]%>&#37;</p>
        </div>
      </div>
    </div>
    <div class="col s12 m6 l4">
      <div class="card" id="weather-card2">
        <div class="center">
          <% time = DateTime.strptime(@forecast_data["hourly"]["data"][1]["time"].to_s, '%s')%>
          <% time = time.in_time_zone(@forecast_data["timezone"])%>
          <p><%= time.strftime('%I:%M%p')%> Forecast:</p>
          <p id="summary"><%= @forecast_data["hourly"]["data"][1]["summary"] %></p>
          <p>Temp: <%= @forecast_data["hourly"]["data"][1]["temperature"].to_i %> &deg;F</p>
          <p>Chance of Rain: <%= @forecast_data["hourly"]["data"][1]["precipProbability"] %>&#37;</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <% if @forecast_data["alert"] %>
      <% @forecast_data["alert"].each do |alert|%>
        <div class="col s12 m6 l4">
          <div class="card red" id="weather-card3">
            <% time = DateTime.strptime(alert["expires"].to_s, '%s')%>
            <% time = time.in_time_zone(@forecast_data["timezone"])%>
            <p>EMERGENCY ALERT:</p>
            <p><%= @forecast_data["alert"]["title"] %></p>
            <p>Expires at: <%= time.strftime('%r')%></p>
            <p>Description: <%= @forecast_data["alert"]["description"].to_i %> &deg;F</p>
            <a href="<%= @forecast_data["alert"]["uri"] %>">More Information</a>
          </div>
        </div>
        <% end %>
    <% end %>
  </div>
  <div class="row">
    <div class="col s12 center">
      <a class="btn light-blue modal-trigger2" href="#modal2">Add New Dog To Pack</a>
    </div>
    <div id="modal2" class="modal">
      <div class="modal-content">
        <h4>Add Dog</h4>
        <%= render partial: "new"%>
      </div>
    </div>
  </div>
  <% @dogs.each do |dog|%>
    <%= render partial: "profile", locals: {dog: dog} %>
  <% end %>
</div>

app/views/dogs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <h3 class="left">Register Your Dog</h3>
    </div>
    <%= form_for(:dog, url: user_dogs_path(@user.id), :html => {:class => "col s12"}) do |f| %>
      <div class="row">
        <div class="input-field col s6 center">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6 center">
          <%= f.label :bio %>
          <%= f.text_area :bio, :class => "materialize-textarea" %>
        </div>
      </div>
      <div class="file-field input-field avatar">
        <div class="btn light-blue">
          <span>Upload Profile Picture</span>
          <%= f.file_field :avatar %>
        </div>
        <input class="file-path validate" type="text"/>
      </div>
      <%= f.hidden_field :owner_id, :value => current_user.id %>
      <%= f.submit :class => "btn light-blue", :value => "Register Dog"%>
    <% end %>
  </div>
</div>

app/views/dogs/show.html.erb
<div id="get_dog" name="<%= @dog.id %>"> </div>
<div class="container">
  <h1 class="center"><%= @dog.name %></h1>
  <div class="section">
    <div class="row">
      <div class="center">
        <%= image_tag @dog.avatar.url(:medium, :class => "circle responsive-img") %>
      </div>
      <% if check_friend_status?(@dog) == false %>
        <% if @dog.owner_id != current_user.id %>
          <a class="btn tooltipped" data-position="bottom" data-delay="50" data-tooltip="Follow <%= @dog.name %>" id="add-friend" name="<%= @dog.id %>"><i class="mdi-social-plus-one"></i></a>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="card light-blue">
      <div class="card-content white-text">
        <span class="card-title">About Me</span>
        <p><%= @dog.bio %></p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="card light-blue">
      <div class="card-content white-text">
        <span class="card-title">Dogs <%= @dog.name %> Follows</span>
        <ul class="collection">
          <% @dog.followings.each do |friend| %>
            <li class="collection-item avatar">
              <a href="/dogs/<%= friend.id %>">
                <span class="title"><%=friend.name%></span>
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>