config/routes.rb
Rails.application.routes.draw do

  get "/" => 'home#index'
  post "/send_text_message" =>"text_messages#send_text_message"

  get "/users/check_messages" => "users#check_messages"

  resources :sessions, only: [:new, :create, :destroy]

  resources :users, except: :delete do
    resources :dogs, only: [:index, :create, :delete]
  end

  resources :messages, only: [:new, :create, :show, :index] do
    resources :comments, module: :messages

  end

  resources :direct_conversations, only: [:index, :show, :new, :create] do
    resources :private_messages, only: [:create]
  end

  resources :dogs, except: [:create, :edit, :delete] do
    resources :dog_connections, only: [:new, :create, :delete]
  end

  resources :events do
    resources :comments, module: :events
    resources :event_invitations, only: [:create, :destroy]
  end

  resources :maps, only: [:index]
  get '/maps/data' => 'maps#data'
  get '/maps/pet_stores' => 'maps#pet_stores'
  get '/maps/dog_parks' => 'maps#dog_parks'
  post '/users/sync_location' => 'users#sync_location'

  post '/dogs/sync_location' => 'dogs#sync_location'

  get '/users' => 'user#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper
  def index
    if current_user
      redirect_to "/users/#{current_user.id}"
    else
      render :'home/index', :layout => false
    end
  end

end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hey9</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="parallax-container">
        <div class="parallax"><img src="<%= image_url('Dog play date.jpg') %>"></div>
    </div>
    <div class="section white">
      <div class="row container">
        <div class="col s12 l4">
          <img src="<%= image_url('hey-9_logo2.png')%>" class="responsive-img center" style="height: 300px;">
        </div>
        <div class="col s12 l8">
          <p class="flow-text">Hey-9 - the four-legged social network</p>
          <p class="flow-text">  In today's society, socialization is like water- we need it, but we're not the only ones.  Our dogs are just as chatty as we are, and benefit immensely
          from developing lasting relationships.  As their owners, its our responsibility to make
          sure our furry friends get what they need.  Meet dogs, find events, make a community.
        </div>
      </div>
      <div class="row container">
        <h1><%= link_to "Register", new_user_path %></h1>
        <div class="divider"></div>
        <h1><%= link_to "Login", new_session_path %></h2>
      </div>
    </div>
      <div class="parallax-container">
        <div class="parallax"><img src="<%= image_url('dog-running.JPG')%>"></div>
      </div>
  </body>
</html>