config/routes.rb
Rails.application.routes.draw do

  get "/" => 'home#index'
  post "/send_text_message" =>"text_messages#send_text_message"

  get "/users/check_messages" => "users#check_messages"

  resources :sessions, only: [:new, :create, :destroy]

  resources :users, except: :delete do
    resources :dogs, only: [:index, :create, :delete]
  end

  resources :messages, only: [:new, :create, :show, :index] do
    resources :comments, module: :messages

  end

  resources :direct_conversations, only: [:index, :show, :new, :create] do
    resources :private_messages, only: [:create]
  end

  resources :dogs, except: [:create, :edit, :delete] do
    resources :dog_connections, only: [:new, :create, :delete]
  end

  resources :events do
    resources :comments, module: :events
    resources :event_invitations, only: [:create, :destroy]
  end

  resources :maps, only: [:index]
  get '/maps/data' => 'maps#data'
  get '/maps/pet_stores' => 'maps#pet_stores'
  get '/maps/dog_parks' => 'maps#dog_parks'
  post '/users/sync_location' => 'users#sync_location'

  post '/dogs/sync_location' => 'dogs#sync_location'

  get '/users' => 'user#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  acts_as_mappable
  
  has_many :event_invitations
  has_many :comments, as: :commentable
  has_many :invitees, through: :event_invitations, foreign_key: "invitee_id"

  belongs_to  :creator, class_name: :User

  validates :creator, :event_start, :event_end, :description, presence: true
end

app/controllers/events/comments_controller.rb
class Events::CommentsController < CommentsController
  before_action :set_commentable



  private

  def set_commentable
    @commentable = Event.find(params[:event_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include ApplicationHelper
  require 'net/https'
  require 'open-uri'
  before_action :require_login
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @user = User.find_by(id: current_user.id)
    @events = []
    if @user.lat && @user.lng
      @location = gen_neighborhood
      @users = User.within(2, :origin => location_get).all
      @users.each do |user|
        user.events.each do |event|
          @events << event
        end
      end
       @events.sort!{|a,b| a.created_at <=> b.created_at}
    end

  end

  def new
    @event = Event.new
  end

  def create
    location_event = params['event']['location'].gsub(" ", "+")
      url = URI.parse("https://maps.googleapis.com/maps/api/geocode/json?address=#{location_event}&key=#{Rails.application.secrets.google_api_key}")
      response = Net::HTTP.get_response(url)
      body = JSON.parse(response.body)
      lat = body['results'][0]["geometry"]["location"]["lat"]
      lng = body['results'][0]["geometry"]["location"]["lng"]
      @event = current_user.events.new(event_params)
      @event.update_attributes(:lat => lat, :lng => lng)
      p @event
    if @event.save
      redirect_to @event
    else
      render :new
    end

  end

  def show
    @event = Event.find_by(id: params[:id])
    @user = User.find_by(id: @event.creator_id)
    @location = [@event.lat, @event.lng]
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event
    else
      render :edit
    end

  end

  def destroy
    @event.destroy
    redirect_to current_user
  end

  def event_data

  end

  private

  def set_event
    if current_user
      @event = Event.find(params[:id])
    end
  end

  def event_params
    params.require(:event).permit(:location, :event_start, :event_end, :description, :public)
  end

end

app/views/events/_comments.html.erb
<ul class="collection">
  <% commentable.comments.each do |comment| %>
    <li class="collection-item">
      <p><%= comment.content %></p>
      <p><%= comment.commenter.username %></p>
    </li>
  <% end %>
</ul>

app/views/events/_comments_form.html.erb
<div class="row">
  <%= form_for [commentable, Comment.new], :html => {:class => "col s12"} do |f| %>
    <div class="input-field col s12">
      <%= f.text_area :content, :class => "materialize-textarea", placeholder: "Add a comment" %>
    </div>
    <%= f.submit(:class => "btn light-blue", :value => "Comment")%>
  <% end %>
</div>

app/views/events/_event.html.erb
<div class="col s12 m6 l6">
  <a href="/events/<%= event.id %>" class="white-text">
    <div class="card hoverable light-blue">
      <h5 class="center truncate"><%= event.description %> </h5>
      <p class="center"><%= event.event_start.strftime('%D') %> @ <%= event.event_start.strftime('%r') %></p>
      <p class="center"><%= event.location %> </p>
    </div>
  </a>
</div>

app/views/events/_event_show.html.erb
<div class="card teal lighten-4">
  <p class="center"><%= event.description %></p>
</div>
<div class="divider"></div>
<div class="row">
  <div class="col s12 l4">
    <% if current_user.id == event.creator_id %>
      <a class="btn light-blue modal-trigger4" href="#modal4">Edit Event</a>
      <div id="modal4" class="modal">
        <div class="modal-content">
          <%= render partial: "form"%>
        </div>
      </div>
    <% end %>
    <h4>Address: </h4>
    <p><%= event.location %></p>
    <h4>Day: </h4>
    <p><%= event.event_start.strftime("%A, %B %d, %Y")%></p>
    <h4>Time: </h4>
    <p> <%= event.event_start.strftime("%I:%M%p")%> - <%= event.event_end.strftime("%I:%M%p") %></p>
  </div>
  <div class="col s12 l4">
    <% if event.comments %>
      <%= render partial: "events/comments", locals: {commentable: event} %>
    <% end %>
    <% if @current_user %>
      <%= render partial: "events/comments_form", locals: {commentable: event} %>
    <% end %>
  </div>
  <div class="col s12 l4">
    <% current_user.dogs.each do |dog| %>
      <% if !event.invitees.include?(dog)%>
          <a class="dropdown-button btn light-blue" href="#" data-activates="dropdown10">Join Event</a>
      <% end %>
    <% end %>
        <ul id="dropdown10" class="dropdown-content">
        <% current_user.dogs.each do |dog| %>
        <li><%= link_to "#{dog.name}",  event_event_invitations_path(:event_id => params[:id], :invitee_id => dog.id), :method => :post %></li>
        <% end %>
      </ul>
    <h5>Attending</h5>
    <div class="row">
      <div class="col s8 m4 l2 green-text">
        <% event.invitees.uniq.each do |dog|%>
            <h5><%= link_to "#{dog.name}", dog_path(dog) %></h5>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<div class="container">
  <div class="row">
  <%= form_for(:event, :html => {:class => "col s8 offset-l2"} )do |f| %>
    <div class="row">
      <div class="input-field col s12">
      <%= f.text_field :location,  placeholder: "123 Main St, Chicago, IL, 60601", :id => "event-location"  %>
      </div>
    </div>
    <div class="row">
      <%= f.label :event_start %>
      <%= f.datetime_field :event_start, placeholder: "YYYY/MM/DD", :class => "datepicker" %>
      <%= f.datetime_field :event_start, placeholder: "HH:MM" %>
    </div>
    <div class="row">
      <%= f.label :event_end %>
      <%= f.datetime_field :event_end, placeholder: "YYYY/MM/DD HH:MM", :class => "datepicker" %>
      <%= f.datetime_field :event_end, placeholder: "HH:MM" %>
    </div>
    <div class="row">
      <%= f.text_area :description, placeholder: "Enter event description here", :class => "materialize-textarea" %>
    </div>

     <div class="row">
      <%= f.check_box :public %>
      <%= f.label "public" %>
    </div>
      <%= f.submit "Create event", :class => "btn light-blue", :id => "event-button" %>
  <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<h1>Edit event</h1>

<%= render "form" %>

app/views/events/index.html.erb
<div class="container">
  <div class="section">
    <div class="row">
      <div class="col s12 l4">
        <h4 class="center">Your Events</h4>
        <div class="card">
          <a class="btn light-blue modal-trigger2" href="#modal3">Create an Event</a>
          <div id="modal3" class="modal">
            <div class="modal-content">
              <h4>New Event</h4>

              <%= render partial: "form"%>
            </div>
          </div>
          <div class="row">
            <%= render partial: "event", collection: current_user.events %>
          </div>
        </div>
      </div>
      <div class="col s12 l4">
        <h4 class="center">Community Events</h4>
        <div class="card">
          <div class="row">
            <%= render partial: "event", collection: @events %>
          </div>
        </div>
      </div>
      <div class="col s12 l4">
        <h4 class="center">Events Your Pack is Attending</h4>
        <div class="card">
          <div class="row">
            <%= render partial: "event", collection: dog_events(current_user.dogs) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<%= render "form" %>

app/views/events/show.html.erb
<div id="event-map" name="<%= @event.lat %>">

</div>

<div class="container">
  <h4>This is <%= @user.username %>'s Event</h4>
  <h5><a href="/direct_conversation">Send <%= @user.username %> a private message</a></h5>
  <div id='event-lng' name="<%= @event.lng %>">


  </div>

  <%= render partial: "event_show", locals: {event: @event} %>


</div>

  <script type="text/javascript">

  var map

 var lat = $("#event-map").attr('name');
 var lng = $("#event-lng").attr('name');
  lat = parseFloat(lat);
  lng = parseFloat(lng);

function initMap() {
  map = new google.maps.Map(document.getElementById('event-map'), {
    center: {lat: lat, lng: lng},
    zoom: 16
  });

var marker = new google.maps.Marker({
    map: map,
    position: {lat: lat, lng: lng},
  });
}

     </script>
     <script async defer
       src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.secrets.google_api_key %>&callback=initMap">
     </script>