config/routes.rb
Rails.application.routes.draw do

  get "/" => 'home#index'
  post "/send_text_message" =>"text_messages#send_text_message"

  get "/users/check_messages" => "users#check_messages"

  resources :sessions, only: [:new, :create, :destroy]

  resources :users, except: :delete do
    resources :dogs, only: [:index, :create, :delete]
  end

  resources :messages, only: [:new, :create, :show, :index] do
    resources :comments, module: :messages

  end

  resources :direct_conversations, only: [:index, :show, :new, :create] do
    resources :private_messages, only: [:create]
  end

  resources :dogs, except: [:create, :edit, :delete] do
    resources :dog_connections, only: [:new, :create, :delete]
  end

  resources :events do
    resources :comments, module: :events
    resources :event_invitations, only: [:create, :destroy]
  end

  resources :maps, only: [:index]
  get '/maps/data' => 'maps#data'
  get '/maps/pet_stores' => 'maps#pet_stores'
  get '/maps/dog_parks' => 'maps#dog_parks'
  post '/users/sync_location' => 'users#sync_location'

  post '/dogs/sync_location' => 'dogs#sync_location'

  get '/users' => 'user#index'

end

app/models/private_message.rb
class PrivateMessage < ActiveRecord::Base
  belongs_to :user
  belongs_to :conversation, class_name: :DirectConversation
end

app/controllers/private_messages_controller.rb
class PrivateMessagesController < ApplicationController
  include ApplicationHelper
  before_action :require_login

  def show
    set_private_message
  end

  def create
    @private_message = PrivateMessage.new private_message_params
    @private_message.user = current_user
    @convo = DirectConversation.find(params[:direct_conversation_id])
    @convo.private_messages << @private_message
    if @private_message.save
      if request.xhr?
        render :partial => 'private_messages/private_message', :layout => false, locals: {message: @private_message}
      else
        redirect_to :back
      end
    else
      if request.xhr?
        status 422
      else
        redirect_to :back
      end
    end
  end

  private

  def set_private_message
    if current_user
      @private_message = PrivateMessage.find(params[:id])
    end
  end

  def private_message_params
    params.require(:private_message).permit(:content)
  end
end

app/views/private_messages/_form.html.erb
<div class="row">
  <%= form_for private_message, as: :private_message, url:  direct_conversation_private_messages_path(direct_conversation), html: {:class => "new_private_message col s12"} do |f| %>
    <div class="input-field col s12">
      <%= f.text_area :content, :class => "materialize-textarea", placeholder: "Write a new message" %>
    </div>
    <%= f.submit :class => "btn-flat", value: "Send message" %>
  <% end %>
</div>

app/views/private_messages/_private_message.html.erb
<% if message.content %>
  <ul class="collection">
    <% if message.user.username == current_user.username %>
      <li class="collection-item right"><p style="border-radius: 8px;" class="indigo lighten-4"><b>you:</b> <%= message.content %><br><b>Sent on:</b> <%= message.created_at.strftime('%c') %></p></li>
    <% else %>
      <li class="collection-item left"><p style="border-radius: 8px;" class="amber lighten-4"><b><%= message.user.username %>:</b> <%= message.content %><br><b>Sent on:</b> <%= message.created_at.strftime('%c') %></p></li>
    <% end %>
  </ul>
<% end %>